#!/bin/bash
# Sync visualization files from private repo to public repo
# Run this after making changes to visualization code

set -e

PRIVATE_DIR="$(pwd)"
PUBLIC_DIR="../trait-interp-viz"

# Check we're in the right place
if [ ! -f "visualization/serve.py" ]; then
    echo "❌ Error: Must run from trait-interp root directory"
    exit 1
fi

if [ ! -d "$PUBLIC_DIR" ]; then
    echo "❌ Error: Public repo not found at $PUBLIC_DIR"
    echo "Create the public repo at $PUBLIC_DIR first"
    exit 1
fi

echo "📋 Syncing visualization files to public repo..."
echo ""

# Visualization code (main directory)
rsync -av --delete \
    --exclude='.git' \
    --exclude='__pycache__' \
    --exclude='*.pyc' \
    visualization/ "$PUBLIC_DIR/visualization/"

# Configuration files (CRITICAL - required at runtime)
rsync -av config/paths.yaml "$PUBLIC_DIR/config/"

# Documentation (CRITICAL - loaded by viz)
mkdir -p "$PUBLIC_DIR/docs"
rsync -av docs/overview.md "$PUBLIC_DIR/docs/"

# Analysis scripts (CRITICAL - called by serve.py)
# Only sync data_checker.py, delete any stale files
mkdir -p "$PUBLIC_DIR/analysis"
rsync -av --delete --include='data_checker.py' --exclude='*' analysis/ "$PUBLIC_DIR/analysis/"

# Utils (for Railway)
mkdir -p "$PUBLIC_DIR/utils"
rsync -av \
    utils/railway_pull_r2.sh \
    utils/paths.py \
    utils/vectors.py \
    utils/model.py \
    "$PUBLIC_DIR/utils/"

# Inference (Modal backend support)
mkdir -p "$PUBLIC_DIR/inference"
rsync -av inference/modal_inference.py "$PUBLIC_DIR/inference/"

# Note: Prompts are NOT synced - they live in experiments/{exp}/inference/prompts/
# and come from the R2 bucket via Railway volume

# Auto-generate requirements.txt for Railway (Modal backend)
cat > "$PUBLIC_DIR/requirements.txt" << 'EOF'
# Auto-generated by update_viz_repo.sh - DO NOT EDIT MANUALLY
PyYAML==6.0.2
fire==0.7.0
modal
torch
transformers
traitlens @ git+https://github.com/ewernn/traitlens.git
EOF
echo "✅ Updated requirements.txt for Modal backend"

echo "✅ Files synced!"
echo ""
echo "📤 Committing and pushing to public repo..."

cd "$PUBLIC_DIR"

# Check if there are changes
if git diff --quiet && git diff --cached --quiet; then
    echo "No changes to commit"
else
    git add .
    git commit -m "Update visualization from private repo"
    git push origin main
    echo "✅ Pushed to public repo → Railway will auto-redeploy"
fi

cd "$PRIVATE_DIR"
echo ""
echo "Done!"
